services:
  - type: web
    name: kqueue
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://-/kqueue
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: -
      - key: ALLOWED_ORIGIN
        value: -
      - key: NODE_ENV
        value: production
